apiVersion: compute.google.golang.org/v1
kind: Firewall
metadata:
  name: example
spec:
  name: example-allow-http
  description: allow http traffic from anywhere
  allowed:
    - IPProtocol: tcp
      ports: ["80"]
  network: global/networks/default
  sourceRanges: ["0.0.0.0/0"]
  targetTags: ["allow-http"]
