apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: gcp-cloud-compute-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - addresses.compute.gce
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - images.compute.gce
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - compute.gce
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - compute.google.golang.org
  resources:
  - '*'
  - images
  - firewalls
  - networks
  - subnetworks
  - forwardingrules
  - targetpools
  - instances
  verbs:
  - '*'
